title: Newb1e's Personal Blog
description: Simple Blog for newb1e.

url: https://jihoi-kim.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

remote_theme : https://github.com/brianmaierjr/long-haul

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: JIHOI-KIM
  email: pascal4847@gmail.com


disqus:
    shortname: brianmaierjr
