title: Newb1e's Blog
description: Personal Blog for newb1e.

url: https://jihoi-kim.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

header: large
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

social:
  github: JIHOI-KIM
  email: pascal4847@gmail.com

